# Generated by Django 3.1.5 on 2021-01-29 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0003_auto_20210126_1852'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bridges', '0004_auto_20210126_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_as_bridge', to='bridges.bridge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_as_vehicle', to='vehicles.vehicle')),
            ],
        ),
    ]
