# Generated by Django 3.1.5 on 2021-02-01 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bridges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgeupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bridge',
            name='users',
            field=models.ManyToManyField(related_name='bridges', through='bridges.BridgeUpdate', to=settings.AUTH_USER_MODEL),
        ),
    ]
