# Generated by Django 3.1.5 on 2021-01-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0003_auto_20210126_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bridge',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
