# Generated by Django 3.1.5 on 2021-02-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tunnel_category',
            field=models.CharField(blank=True, choices=[('', 'No tunnel category'), ('A', 'Tunnel category A'), ('B', 'Tunnel category B'), ('C', 'Tunnel category C'), ('D', 'Tunnel category D'), ('E', 'Tunnel category E')], max_length=1, verbose_name='vehicle tunnel category'),
        ),
    ]
