# Generated by Django 3.1.5 on 2021-01-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='update',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gross_weight',
            field=models.IntegerField(blank=None, null=True, verbose_name='vehicle gross weight'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_hazardous_goods',
            field=models.BooleanField(default=False, verbose_name='has hazardous goods'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=None, max_length=200, null=True, verbose_name='vehicle name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='truck_type',
            field=models.CharField(choices=[('S', 'Straight'), ('T', 'Tractor')], default='S', max_length=1, verbose_name='vehicle type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tunnel_category',
            field=models.CharField(choices=[('A', 'Tunnel category A'), ('B', 'Tunnel category B'), ('C', 'Tunnel category C'), ('D', 'Tunnel category D'), ('E', 'Tunnel category E')], default='A', max_length=1, verbose_name='vehicle tunnel category'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last vehicle update date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vehicle creation date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='vehicle height'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='vehicle length'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='vehicle width'),
        ),
        migrations.DeleteModel(
            name='Assovehicle',
        ),
    ]
