# Generated by Django 3.1.5 on 2021-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210203_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='truck_type',
            field=models.CharField(choices=[('C', 'Car'), ('S', 'Straight'), ('T', 'Tractor')], default='S', max_length=1, verbose_name='vehicle type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tunnel_category',
            field=models.CharField(blank=True, choices=[('', 'No tunnel category'), ('B', 'Tunnel category B'), ('C', 'Tunnel category C'), ('D', 'Tunnel category D'), ('E', 'Tunnel category E')], max_length=1, verbose_name='vehicle tunnel category'),
        ),
    ]
