# Generated by Django 3.1.5 on 2021-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210122_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='gross_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='vehicle gross weight'),
        ),
    ]
